sf_web_app_cms_homepage:
    path:     /
    defaults: { _controller: SfWebAppCmsBundle:Default:index }

sf_web_app_cms_fichepage:
    path:     /fiche
    defaults: { _controller: SfWebAppCmsBundle:Default:fiche }

sf_web_app_cms_acteurspage:
    path:     /acteurs
    defaults: { _controller: SfWebAppCmsBundle:Default:acteurs }